### PR TITLE
Use proper 32bit libfacenet.so for arm devices

### PR DESCRIPTION
**Pull request by SpasilliumNexus**
The previous library was intended for 64bit (arm64) devices. However, using this on an 32bit (arm) device caused Trusted Face to not work, and giving "E/AndroidRuntime(5742): java.lang.UnsatisfiedLinkError: dlopen failed: "/system/lib/libfacenet.so" is 64-bit instead of 32-bit" in logcat.

Taken from the zip shared by @Subinsmani: https://github.com/opengapps/opengapps/issues/555#issuecomment-356595517

### CODE REVIEW

**Comment by ishubhamsingh** [comment]
The facelock lib in that zip is taken from nougat and hence it depends on libprotobuff from nougat. So the libfacenet.so in that zip also needs libprotobuf-cpp-shit.so(Which is just libprotobuff taken from nougat ROM) , that too is present in that zip, so need to add that too.

**Comment by SpasilliumNexus** [comment]
@ishubhamsingh could you make a nandroid and test out my zips with only libfacenet swapped out on a clean install? I've posted builds for [8.0 and 8.1 here](https://forum.xda-developers.com/showthread.php?t=3743495&p=75648443)

One person tested two ROMs on a OnePlus One and reported that Face Unlock works on both after flashing it.

**Comment by ishubhamsingh** [comment]
@SpasilliumNexus The thing is my rom builds have haxx for facelock libs so it works out with any unofficial build of opengapps (nano +)
Vendor commmits:-
https://github.com/AospExtended-Devices/proprietary_vendor_motorola/commit/db48d20b57a7c4e132ff4a071dd254724152689e

https://github.com/AospExtended-Devices/proprietary_vendor_motorola/commit/ef645f3a6a3ae830735d2a70b3b668c6741da555

Tree side commits:-
https://github.com/AospExtended-Devices/device_motorola_msm8916-common/commit/7946bea8b2ca8995b09fbe33ba8827ffdc24c686
https://github.com/AospExtended-Devices/device_motorola_msm8916-common/commit/ff4e60d22db6b8998550a9447b64efe869caea01
https://github.com/AospExtended-Devices/device_motorola_msm8916-common/commit/eece668e6e204abbfc6e14078b777586335aa0e4

And probably that zip shared by @Subinsmani contains the same libs as in above commit.

**Comment by SpasilliumNexus** [comment]
@ishubhamsingh noted. thanks. building now to see if the extra library gets installed too.

**Comment by SpasilliumNexus** [comment]
This is a dirty fix to get that extra library installed as I am still a bit new to scripting. "Dirty" as in additions to the installer may not be nice looking. Any suggestions to improve on it is greatly welcomed. But for now, it does the job.

Screenshot: https://i.imgur.com/Drwpc8M.png

**Comment by osm0sis** [comment]
@NicholasBuse

**Comment by jamuir** [comment]
nice to see a PR for this issue.

Note that SquallATF reported this defect on 15 Jan:

https://github.com/opengapps/aosp_build/issues/163

**Comment by nezorflame** [comment]
@jamuir unfortunately maintainers aren't very active here...

**Pull request merged**
